const state={ cocktails:[], ingredients:[] }

function debounce(fn, wait){ let t; return (...a)=>{ clearTimeout(t); t=setTimeout(()=>fn(...a), wait) } }

async function loadMeta(){ const m=await window.apiClient.request('/cocktails/meta'); const cat=document.getElementById('selCategory'); const base=document.getElementById('selBase'); const tag=document.getElementById('selTag'); m.categories.forEach(v=>{ const o=document.createElement('option'); o.value=v; o.textContent=v; cat.appendChild(o) }); m.bases.forEach(v=>{ const o=document.createElement('option'); o.value=v; o.textContent=v; base.appendChild(o) }); m.tags.forEach(v=>{ const o=document.createElement('option'); o.value=v; o.textContent=v; tag.appendChild(o) }) }

function addIngredientChip(name){ if(state.ingredients.includes(name)) return; state.ingredients.push(name); const el=document.getElementById('selectedIngredients'); const chip=document.createElement('span'); chip.className='badge bg-secondary animate__animated animate__zoomIn'; chip.textContent=name; chip.onclick=()=>{ const i=state.ingredients.indexOf(name); if(i>=0){ state.ingredients.splice(i,1); chip.remove(); render() } }; el.appendChild(chip); render() }

function renderSuggest(items){ const s=document.getElementById('ingSuggest'); s.innerHTML=''; items.forEach(it=>{ const a=document.createElement('a'); a.className='list-group-item list-group-item-action'; a.textContent=it.name; a.onclick=()=>{ addIngredientChip(it.name); s.innerHTML='' }; s.appendChild(a) }) }

function scoreByPrefs(c){ const prefs = {}; try{ const pStr=localStorage.getItem('userPrefs'); if(pStr) Object.assign(prefs, JSON.parse(pStr)) }catch{} let s=0; if(prefs.preferred_categories && c.categories) s+= c.categories.filter(x=> prefs.preferred_categories.includes(x)).length; if(prefs.preferred_ingredients && c.ingredientsNames) s+= c.ingredientsNames.filter(x=> prefs.preferred_ingredients.includes(x)).length; return s }

function render(){ const el=document.getElementById('results'); el.innerHTML=''; const cat=document.getElementById('selCategory').value||null; const base=document.getElementById('selBase').value||null; const tag=document.getElementById('selTag').value||null; const sort=document.getElementById('selSort').value; let list=[...state.cocktails]; if(cat) list=list.filter(c=> (c.categories||[]).includes(cat)); if(base) list=list.filter(c=> (c.bases||[]).includes(base)); if(tag) list=list.filter(c=> (c.tags||[]).includes(tag)); if(state.ingredients.length){ list=list.filter(c=> state.ingredients.every(n=> (c.ingredientsNames||[]).includes(n))) } if(sort==='recent'){ list.sort((a,b)=> new Date(b.created_at||0)-new Date(a.created_at||0)) } else if(sort==='prep_time'){ list.sort((a,b)=> (a.prep_time_minutes||999)-(b.prep_time_minutes||999)) } else if(sort==='difficulty'){ const w={ 'Fácil':1,'Moderado':2,'Avanzado':3 }; list.sort((a,b)=> (w[a.difficulty||'Avanzado'])-(w[b.difficulty||'Avanzado'])) } else if(sort==='preference'){ list.sort((a,b)=> scoreByPrefs(b)-scoreByPrefs(a)) }
  list.forEach(c=>{ const col=document.createElement('div'); col.className='col-md-4'; const card=document.createElement('div'); card.className='card h-100 animate__animated animate__fadeInUp'; const body=document.createElement('div'); body.className='card-body'; const h=document.createElement('h5'); h.className='card-title'; h.textContent=c.name; const p=document.createElement('p'); p.className='card-text'; p.textContent=c.short_description||''; body.appendChild(h); body.appendChild(p); card.appendChild(body); col.appendChild(card); el.appendChild(col) }) }

async function enrich(c){ const ings= await window.apiClient.request(`/cocktails/${c.id}/ingredients`).catch(()=>[]); const categories=(await window.apiClient.request(`/cocktails/meta`)).categories||[]; // fallback; ideally per cocktail
  return { ...c, ingredientsNames:(ings||[]).map(x=> x.Ingredient? x.Ingredient.name : x.name).filter(Boolean), categories:c.categories||categories }
}

async function init(){ if(!localStorage.getItem('authToken')){ window.location.href='login.html'; return } await loadMeta(); const raw=await window.apiClient.getCocktails().catch(()=>[]); state.cocktails = await Promise.all(raw.map(enrich)); const input=document.getElementById('ingInput'); const onType=debounce(async ()=>{ const q=input.value.trim(); if(!q){ document.getElementById('ingSuggest').innerHTML=''; return } const items=await window.apiClient.searchIngredients(q).catch(()=>[]); renderSuggest(items) },300); input.addEventListener('input', onType); render() }

document.addEventListener('DOMContentLoaded', init)
